# Generated by Django 3.1.1 on 2020-09-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tabPath', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Files_Storage',
            },
        ),
    ]
